[tool.poetry]
name = "torchmanager-diffusion"
version = "0.1.15a"
description = "Torchmanager Implementation for Diffusion Model (v0.1.15 alpha)"
authors = ["Kison Ho <unfit-gothic.0q@icloud.com>"]
packages = [
    { include = "diffusion" }
]

[tool.poetry.dependencies]
python = "^3.9"
torchmanager = "^1.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"